import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1716375273355 implements MigrationInterface {
    name = 'InitMigration1716375273355'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "self_wash_halls" DROP CONSTRAINT "self_wash_halls_location_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "cars" DROP CONSTRAINT "cars_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" DROP CONSTRAINT "loyalty_rewards_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" DROP CONSTRAINT "loyalty_rewards_loyalty_reward_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "memberships_membership_type_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_membership_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "wash_halls" DROP CONSTRAINT "wash_halls_location_id_fkey"`);
        await queryRunner.query(`CREATE TABLE "history" ("id" SERIAL NOT NULL, "date" TIMESTAMP NOT NULL, "user_id" integer, "location_id" integer, CONSTRAINT "PK_9384942edf4804b38ca0ee51416" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD "user_id" integer`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "UQ_7c1e2fdfed4f6838e0c05ae5051" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" ALTER COLUMN "is_in_use" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" ALTER COLUMN "is_in_use" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" ALTER COLUMN "is_out_of_service" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" ALTER COLUMN "is_out_of_service" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "cars" DROP COLUMN "license_plate"`);
        await queryRunner.query(`ALTER TABLE "cars" ADD "license_plate" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loyalty_reward_types" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "loyalty_reward_types" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "membership_types" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "membership_types" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "membership_types" ALTER COLUMN "price" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "membership_types" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "membership_types" ADD "currency" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD "start_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD "end_date" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "full_name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_4d69c02b952f9c35c3d03867e43" UNIQUE ("membership_id")`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "address" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "maps_url"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "maps_url" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "latitude" TYPE numeric(9,6)`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "latitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "longitude" TYPE numeric(9,6)`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "longitude" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wash_halls" ALTER COLUMN "is_out_of_service" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wash_halls" ALTER COLUMN "is_out_of_service" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" ADD CONSTRAINT "FK_6d3a8bfdfc5b666af48d2b3f7cd" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars" ADD CONSTRAINT "FK_673bd295e52580c0fb09d0fbbb8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" ADD CONSTRAINT "FK_9d705a0e794576487be4f782f7d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" ADD CONSTRAINT "FK_d397754b0d0d2d7cd103c7679ce" FOREIGN KEY ("loyalty_reward_type_id") REFERENCES "loyalty_reward_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_9dcc7427af59fec317860eec38a" FOREIGN KEY ("membership_type_id") REFERENCES "membership_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "FK_7c1e2fdfed4f6838e0c05ae5051" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_4d69c02b952f9c35c3d03867e43" FOREIGN KEY ("membership_id") REFERENCES "memberships"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "history" ADD CONSTRAINT "FK_ea92daa642af67e2a924a5547d5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "history" ADD CONSTRAINT "FK_226ec6c3eecfcd7f7b966babaa2" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wash_halls" ADD CONSTRAINT "FK_ea90f7f1e66bca94fbfb2205e45" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "wash_halls" DROP CONSTRAINT "FK_ea90f7f1e66bca94fbfb2205e45"`);
        await queryRunner.query(`ALTER TABLE "history" DROP CONSTRAINT "FK_226ec6c3eecfcd7f7b966babaa2"`);
        await queryRunner.query(`ALTER TABLE "history" DROP CONSTRAINT "FK_ea92daa642af67e2a924a5547d5"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_4d69c02b952f9c35c3d03867e43"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_7c1e2fdfed4f6838e0c05ae5051"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "FK_9dcc7427af59fec317860eec38a"`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" DROP CONSTRAINT "FK_d397754b0d0d2d7cd103c7679ce"`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" DROP CONSTRAINT "FK_9d705a0e794576487be4f782f7d"`);
        await queryRunner.query(`ALTER TABLE "cars" DROP CONSTRAINT "FK_673bd295e52580c0fb09d0fbbb8"`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" DROP CONSTRAINT "FK_6d3a8bfdfc5b666af48d2b3f7cd"`);
        await queryRunner.query(`ALTER TABLE "wash_halls" ALTER COLUMN "is_out_of_service" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "wash_halls" ALTER COLUMN "is_out_of_service" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "longitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "longitude" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "latitude" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "locations" ALTER COLUMN "latitude" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "maps_url"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "maps_url" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "address" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "locations" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "locations" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_4d69c02b952f9c35c3d03867e43"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "full_name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "full_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD "status" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD "end_date" date`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD "start_date" date`);
        await queryRunner.query(`ALTER TABLE "membership_types" DROP COLUMN "currency"`);
        await queryRunner.query(`ALTER TABLE "membership_types" ADD "currency" character varying(10)`);
        await queryRunner.query(`ALTER TABLE "membership_types" ALTER COLUMN "price" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "membership_types" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "membership_types" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "loyalty_reward_types" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "loyalty_reward_types" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "cars" DROP COLUMN "license_plate"`);
        await queryRunner.query(`ALTER TABLE "cars" ADD "license_plate" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" ALTER COLUMN "is_out_of_service" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" ALTER COLUMN "is_out_of_service" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" ALTER COLUMN "is_in_use" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" ALTER COLUMN "is_in_use" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP CONSTRAINT "UQ_7c1e2fdfed4f6838e0c05ae5051"`);
        await queryRunner.query(`ALTER TABLE "memberships" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" ADD "status" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" ADD "user_id" integer`);
        await queryRunner.query(`DROP TABLE "history"`);
        await queryRunner.query(`ALTER TABLE "wash_halls" ADD CONSTRAINT "wash_halls_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_membership_id_fkey" FOREIGN KEY ("membership_id") REFERENCES "memberships"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "memberships" ADD CONSTRAINT "memberships_membership_type_id_fkey" FOREIGN KEY ("membership_type_id") REFERENCES "membership_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" ADD CONSTRAINT "loyalty_rewards_loyalty_reward_type_id_fkey" FOREIGN KEY ("loyalty_reward_type_id") REFERENCES "loyalty_reward_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_rewards" ADD CONSTRAINT "loyalty_rewards_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cars" ADD CONSTRAINT "cars_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "self_wash_halls" ADD CONSTRAINT "self_wash_halls_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
